name: profile_view
description: Open Profile Images in instagram like Styles.
version: 1.0.0
homepage: https://github.com/immi420/profile_view
#authors: Imtiaz Ahmad -twitter [its_immi]
repository: https://github.com/immi420/profile_view
issue_tracker: https://github.com/immi420/profile_view/issues
topics:
  - profileview
  - imageview
  - photoview
funding:
  - https://buymeacoffee.com/immi420

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

